<?php

return [
    [
        "block"         => "form_block1",
        "label"         => "会社名",
        "type"          => "text",
        "name"          => "company",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "",
        "options"       => "",
        "placeholder"   => "例）株式会社あつまる",
        "for_bcc"       => "1",
        "thanks_to"     => "",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "お名前",
        "type"          => "text",
        "name"          => "name01",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "",
        "options"       => "KANA=>kana01",
        "placeholder"   => "例）集客　太郎",
        "for_bcc"       => "",
        "thanks_to"     => "",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "部署名",
        "type"          => "text",
        "name"          => "dept",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "",
        "options"       => "",
        "placeholder"   => "例）営業部",
        "for_bcc"       => "1",
        "thanks_to"     => "",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "メールアドレス",
        "type"          => "email",
        "name"          => "email",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "ドメイン指定受信をされている方は「@atsu-maru.co.jp」から受信できるよう設定をお願いいたします。",
        "options"       => "",
        "placeholder"   => "例）yourname@yourdomain.com",
        "for_bcc"       => "",
        "thanks_to"     => "1",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "携帯電話",
        "type"          => "tel",
        "name"          => "tel",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "※お持ちでない方は固定番号をご記入下さい",
        "options"       => "",
        "placeholder"   => "例）09012345678",
        "for_bcc"       => "",
        "thanks_to"     => "",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "お問合せ内容",
        "type"          => "checkbox",
        "name"          => "content",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "",
        "options"       => "
            集客
            採用
            CI
            DX
        ",
        "placeholder"   => "",
        "for_bcc"       => "1",
        "thanks_to"     => "",
        "required"      => "1",
        "attributes"    => "",
    ],
    [
        "block"         => "form_block1",
        "label"         => "今のお困りごと",
        "type"          => "textarea",
        "name"          => "contact",
        "default"       => "",
        "prepend"       => "",
        "append"        => "",
        "header_notice" => "",
        "body_notice"   => "",
        "options"       => "",
        "placeholder"   => "",
        "for_bcc"       => "1",
        "thanks_to"     => "",
        "required"      => "",
        "attributes"    => "",
    ],
];
