export const keys = [
  'block',
  'label',
  'type',
  'name',
  'default',
  'prepend',
  'append',
  'header_notice',
  'body_notice',
  'options',
  'placeholder',
  'for_bcc',
  'thanks_to',
  'required',
  'attributes',
];

export const presets = {
  '汎用テキストフィールド': [
    {
      block: 'step1',
      label: '',
      type: 'text',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用テキストエリア': [
    {
      block: 'step1',
      label: '',
      type: 'textarea',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用チェックボックス': [
    {
      block: 'step1',
      label: '',
      type: 'checkbox',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '選択肢1\n選択肢2\n選択肢3',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用ラジオボタン': [
    {
      block: 'step1',
      label: '',
      type: 'radio',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '選択肢1\n選択肢2\n選択肢3',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用プルダウン': [
    {
      block: 'step1',
      label: '',
      type: 'select',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n選択肢1\n選択肢2\n選択肢3',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用デイトピッカー': [
    {
      block: 'step1',
      label: '日付',
      type: 'datepicker',
      name: 'date',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: 'カレンダーから選択▼',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '汎用パスワード': [
    {
      block: 'step1',
      label: 'パスワード',
      type: 'password',
      name: 'password',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '非表示フィールド': [
    {
      block: 'step1',
      label: '非表示フィールド',
      type: 'hidden',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'タイトル行': [
    {
      block: 'step1',
      label: 'タイトルあああ',
      type: 'title',
      name: '',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'お名前': [
    {
      block: 'step1',
      label: 'お名前',
      type: 'text',
      name: 'name01',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）山田　花子',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: 'autocomplete="name"',
    },
  ],

  'お名前・ふりがな': [
    {
      block: 'step1',
      label: 'お名前',
      type: 'text',
      name: 'name01',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: 'KANA=>kana01',
      placeholder: '例）山田　花子',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: 'autocomplete="name"',
    },
    {
      block: 'step1',
      label: 'ふりがな',
      type: 'text',
      name: 'kana01',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）やまだ　はなこ',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'お名前・フリガナ': [
    {
      block: 'step1',
      label: 'お名前',
      type: 'text',
      name: 'name01',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: 'KATAKANA=>kana01',
      placeholder: '例）山田　花子',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: 'autocomplete="name"',
    },
    {
      block: 'step1',
      label: 'フリガナ',
      type: 'text',
      name: 'kana01',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）ヤマダ　ハナコ',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'お相手のお名前': [
    {
      block: 'step1',
      label: 'お相手のお名前',
      type: 'text',
      name: 'name02',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）山田　太郎',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'お相手のお名前・ふりがな': [
    {
      block: 'step1',
      label: 'お相手のお名前',
      type: 'text',
      name: 'name02',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: 'KANA=>kana02',
      placeholder: '例）山田　太郎',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
    {
      block: 'step1',
      label: 'お相手のふりがな',
      type: 'text',
      name: 'kana02',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）やまだ　たろう',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'お相手のお名前・フリガナ': [
    {
      block: 'step1',
      label: 'お相手のお名前',
      type: 'text',
      name: 'name02',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: 'KATAKANA=>kana02',
      placeholder: '例）山田　太郎',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
    {
      block: 'step1',
      label: 'お相手のフリガナ',
      type: 'text',
      name: 'kana02',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）ヤマダ　タロウ',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '会社名': [
    {
      block: 'step1',
      label: '会社名',
      type: 'text',
      name: 'company',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="organization"',
    },
  ],

  '部署名': [
    {
      block: 'step1',
      label: '部署名',
      type: 'text',
      name: 'dept',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '役職': [
    {
      block: 'step1',
      label: '役職',
      type: 'text',
      name: 'position',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="organization-title"',
    },
  ],

  '電話番号': [
    {
      block: 'step1',
      label: '電話番号',
      type: 'tel',
      name: 'tel',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）000-0000-0000',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  '携帯番号': [
    {
      block: 'step1',
      label: '携帯番号',
      type: 'tel',
      name: 'tel',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）000-0000-0000',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'メールアドレス': [
    {
      block: 'step1',
      label: 'メールアドレス',
      type: 'email',
      name: 'email',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: 'ドメイン指定受信をされている方は「@」から受信できるよう設定をお願いいたします。',
      options: '',
      placeholder: '例）yourname@yourdomain.com',
      for_bcc: false,
      thanks_to: true,
      required: true,
      attributes: '',
    },
  ],

  'メールアドレス・確認': [
    {
      block: 'step1',
      label: 'メールアドレス',
      type: 'email',
      name: 'email',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: 'ドメイン指定受信をされている方は「@」から受信できるよう設定をお願いいたします。',
      options: '',
      placeholder: '例）yourname@yourdomain.com',
      for_bcc: false,
      thanks_to: true,
      required: true,
      attributes: '',
    },
    {
      block: 'step1',
      label: 'メールアドレス（確認）',
      type: 'email',
      name: 'email_again',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '確認のためもう一度同じメールアドレスをご入力ください。',
      options: 'EQUAL=>email',
      placeholder: '例）yourname@yourdomain.com',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  '郵便番号': [
    {
      block: 'step1',
      label: '郵便番号',
      type: 'zip',
      name: 'zip',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: 'ZIP=>pref,address',
      placeholder: '例）000-0000',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '都道府県': [
    {
      block: 'step1',
      label: '都道府県',
      type: 'pref',
      name: 'pref',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'ご住所': [
    {
      block: 'step1',
      label: 'ご住所',
      type: 'address',
      name: 'address',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '性別': [
    {
      block: 'step1',
      label: '性別',
      type: 'radio',
      name: 'gender',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '男性\n女性',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="sex"',
    },
  ],

  '年齢': [
    {
      block: 'step1',
      label: '年齢',
      type: 'text',
      name: 'age',
      default: '',
      prepend: '',
      append: '歳',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '生年月日': [
    {
      block: 'step1',
      label: '生年月日',
      type: 'select',
      name: 'birth_year',
      default: '',
      prepend: '',
      append: '年',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\nYEAR=>-100~+0',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="bday-year"',
    },
    {
      block: 'step1',
      label: '生年月日',
      type: 'select',
      name: 'birth_month',
      default: '',
      prepend: '',
      append: '月',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="bday-month"',
    },
    {
      block: 'step1',
      label: '生年月日',
      type: 'select',
      name: 'birth_day',
      default: '',
      prepend: '',
      append: '日',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: 'autocomplete="bday-day"',
    },
  ],

  '卒業（予定）年月': [
    {
      block: 'step1',
      label: '卒業（予定）年月',
      type: 'select',
      name: 'grad_year',
      default: '',
      prepend: '',
      append: '年',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\nYEAR=>-2~+6',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
    {
      block: 'step1',
      label: '卒業（予定）年月',
      type: 'select',
      name: 'grad_month',
      default: '',
      prepend: '',
      append: '月',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '最終学歴': [
    {
      block: 'step1',
      label: '最終学歴',
      type: 'text',
      name: 'gakureki',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'ご見学希望日': [
    {
      block: 'step1',
      label: 'ご見学希望日',
      type: 'datepicker',
      name: 'res_date',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: 'カレンダーから選択▼',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'ご見学希望時間': [
    {
      block: 'step1',
      label: 'ご見学希望時間',
      type: 'select',
      name: 'res_time',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n9：00～11：00\n11：00～13：00\n13：00～15：00\n15：00～17：00\n17：00～19：00\n19：00以降',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'ご参加人数': [
    {
      block: 'step1',
      label: 'ご参加人数',
      type: 'select',
      name: 'res_people',
      default: '',
      prepend: '',
      append: '名様',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n1\n2\n3\n4\n5\n6',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  '挙式予定時期': [
    {
      block: 'step1',
      label: '挙式予定時期',
      type: 'select',
      name: 'wed_year',
      default: '',
      prepend: '',
      append: '年',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\nYEAR=>3',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
    {
      block: 'step1',
      label: '挙式予定時期',
      type: 'select',
      name: 'wed_month',
      default: '',
      prepend: '',
      append: '月頃',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  '挙式予定人数': [
    {
      block: 'step1',
      label: '挙式予定人数',
      type: 'select',
      name: 'wed_people',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n10名以下\n11～30名\n31～50名\n51～80名\n81～100名\n101～120名\n121名以上',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],

  'LINE ID': [
    {
      block: 'step1',
      label: 'LINE ID',
      type: 'text',
      name: 'line_id',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '例）',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'フェア名': [
    {
      block: 'step1',
      label: 'フェア名',
      type: 'text',
      name: 'fairName',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: 'readonly',
    },
  ],

  'フェア開催日時': [
    {
      block: 'step1',
      label: 'フェア開催日時',
      type: 'text',
      name: 'fairTime',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: 'readonly',
    },
  ],

  'イベント名': [
    {
      block: 'step1',
      label: 'イベント名',
      type: 'text',
      name: 'event_name',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: 'readonly',
    },
  ],

  'イベント開催日時': [
    {
      block: 'step1',
      label: 'イベント開催日時',
      type: 'text',
      name: 'event_time',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: true,
      attributes: 'readonly',
    },
  ],

  'きっかけ': [
    {
      block: 'step1',
      label: 'きっかけ',
      type: 'select',
      name: 'kikkake',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\nホームページ\nSNS\nチラシ\n紹介\n新聞\n雑誌\nその他',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '連絡の取りやすい時間帯': [
    {
      block: 'step1',
      label: '連絡の取りやすい時間帯',
      type: 'select',
      name: 'time',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '\n=>選択\n10:00～11:00\n11:00～12:00\n12:00～13:00\n13:00～14:00\n14:00～15:00\n15:00～16:00\n16:00～17:00\n17:00～18:00\n18:00～19:00\n19:00～20:00',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'ご希望の連絡方法': [
    {
      block: 'step1',
      label: 'ご希望の連絡方法',
      type: 'radio',
      name: 'method',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '電話\nメール\nどちらでも構わない',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '種別': [
    {
      block: 'step1',
      label: '種別',
      type: 'radio',
      name: 'type',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '資料請求\nお問合せ',
      placeholder: '',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  'ご質問・ご要望など': [
    {
      block: 'step1',
      label: 'ご質問・ご要望など',
      type: 'textarea',
      name: 'contact',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '',
      placeholder: '気になることをぜひ教えてください。',
      for_bcc: true,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '添付ファイル': [
    {
      block: 'step1',
      label: '添付ファイル',
      type: 'file',
      name: 'file',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '●MB以下のファイルが添付できます。',
      options: '',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: false,
      attributes: '',
    },
  ],

  '個人情報の取扱について': [
    {
      block: 'step1',
      label: '個人情報の取扱について',
      type: 'checkbox',
      name: 'privacy',
      default: '',
      prepend: '',
      append: '',
      header_notice: '',
      body_notice: '',
      options: '個人情報の取り扱いに同意する',
      placeholder: '',
      for_bcc: false,
      thanks_to: false,
      required: true,
      attributes: '',
    },
  ],
}
